apiVersion: v1
kind: Service
metadata:
  name: {{ template "kube-state-metrics.fullname" . }}
  labels:
    app: {{ template "kube-state-metrics.name" . }}
    component: kube-state-metrics
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  {{- if .Values.prometheusScrape }}
  annotations:
    prometheus.io/scrape: 'true'
  {{- end }}
spec:
  ports:
  - name: http-metrics
    port: 8080
    targetPort: http-metrics
    protocol: TCP
  - name: telemetry
    port: 8081
    targetPort: telemetry
    protocol: TCP
  selector:
    app: {{ template "kube-state-metrics.name" . }}
    component: kube-state-metrics
    release: {{ .Release.Name }}
