apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app: {{ template "k8s-monitor.name" . }}
    component: prometheus
    release: {{ .Release.Name }}
spec:
  type: NodePort
  ports:
  - port: 9090
    targetPort: 9090
  selector:
    app: {{ template "k8s-monitor.name" . }}
    component: prometheus
    release: {{ .Release.Name }}
