{{- if .Values.prometheus.localPersistentVolume }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "prometheus.fullname" . }}
  labels:
    app: {{ template "prometheus.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.prometheus.localPersistentVolume.storage }}
  storageClassName: local-storage
{{- end }}
